apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ipc-workloads
  namespace: flux-system
spec:
  interval: 1m
  path: ./kubernetes/workloads
  prune: true
  sourceRef:
    kind: GitRepository
    name: ipc-platform-config
